# Generated by Django 5.2.7 on 2025-10-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='ip_address',
            field=models.GenericIPAddressField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audit',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout')], max_length=100),
        ),
    ]
