# Generated by Django 5.2.7 on 2025-11-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audit_ip_address_alter_audit_action'),
    ]

    operations = [
    ]
