// This file is generated by the 'node-soap-servicegenerator'
// visit : https://github.com/BreeeZe/node-soap-servicegenerator for more info

var NOT_IMPLEMENTED = {
  Fault: {
    Code: {
      Value: "soap:client"
    },
    Reason: {
      Text: "Method not implemented"
    }
  }
};
var exports = module.exports = {};

exports.MediaService = {
  MediaService: {
    Media: {
      GetProfiles: function(args) {
        return {
          Profiles: [
            {
              Name: "MainStream",
              attributes: { token: "Profile_1" },
              VideoEncoderConfiguration: {
                attributes: { token: "VideoEncCfg_1" },
                Name: "Main Stream Encoder",
                Encoding: "H264",
                Resolution: { Width: 1920, Height: 1080 },
                Quality: 1
              }
            },
            {
              Name: "SecondStream",
              attributes: { token: "Profile_2" },
              VideoEncoderConfiguration: {
                attributes: { token: "VideoEncCfg_2" },
                Name: "Second Stream Encoder",
                Encoding: "H264",
                Resolution: { Width: 1280, Height: 720 },
                Quality: 1
              }
            }
          ]
        };
      },

      GetProfile: function(args) {
        const profiles = {
          "Profile_1": {
            Name: "MainStream",
            attributes: { token: "Profile_1" },
            VideoEncoderConfiguration: {
              attributes: { token: "VideoEncCfg_1" },
              Name: "Main Stream Encoder",
              Encoding: "H264",
              Resolution: { Width: 1920, Height: 1080 },
              Quality: 1
            }
          },
          "Profile_2": {
            Name: "SecondStream",
            attributes: { token: "Profile_2" },
            VideoEncoderConfiguration: {
              attributes: { token: "VideoEncCfg_2" },
              Name: "Second Stream Encoder",
              Encoding: "H264",
              Resolution: { Width: 1280, Height: 720 },
              Quality: 1
            }
          }
        };
        return { Profile: profiles[args.ProfileToken] };
      },

      GetStreamUri: function(args) {
        const uris = {
          "Profile_1": "rtsp://admin:Aragats777@192.168.0.21:3333/stream",
          "Profile_2": "rtsp://admin:Aragats777@192.168.0.21:1111/"
        };
        return {
          MediaUri: {
            Uri: uris[args.ProfileToken],
            InvalidAfterConnect: false,
            InvalidAfterReboot: false,
            Timeout: "PT60S"
          }
        };
      }
    }
  }
};
