# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import camera_pb2 as camera__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in camera_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CameraServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTelemetry = channel.unary_unary(
                '/camera.CameraService/GetTelemetry',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.TelemetryResponse.FromString,
                _registered_method=True)
        self.MovePTZ = channel.unary_unary(
                '/camera.CameraService/MovePTZ',
                request_serializer=camera__pb2.MovePTZRequest.SerializeToString,
                response_deserializer=camera__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SetZoom = channel.unary_unary(
                '/camera.CameraService/SetZoom',
                request_serializer=camera__pb2.SetZoomRequest.SerializeToString,
                response_deserializer=camera__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetCurrentZoom = channel.unary_unary(
                '/camera.CameraService/GetCurrentZoom',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.ZoomResponse.FromString,
                _registered_method=True)
        self.SetSpeed = channel.unary_unary(
                '/camera.CameraService/SetSpeed',
                request_serializer=camera__pb2.SetSpeedRequest.SerializeToString,
                response_deserializer=camera__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SetManualGps = channel.unary_unary(
                '/camera.CameraService/SetManualGps',
                request_serializer=camera__pb2.ManualGpsRequest.SerializeToString,
                response_deserializer=camera__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetCrossPositions = channel.unary_unary(
                '/camera.CameraService/GetCrossPositions',
                request_serializer=camera__pb2.CrossPositionsRequest.SerializeToString,
                response_deserializer=camera__pb2.CrossPositionsResponse.FromString,
                _registered_method=True)
        self.GetPTZPosition = channel.unary_unary(
                '/camera.CameraService/GetPTZPosition',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.PTZPositionResponse.FromString,
                _registered_method=True)
        self.SendControl = channel.unary_unary(
                '/camera.CameraService/SendControl',
                request_serializer=camera__pb2.SendControlRequest.SerializeToString,
                response_deserializer=camera__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SetPTZDirection = channel.unary_unary(
                '/camera.CameraService/SetPTZDirection',
                request_serializer=camera__pb2.SetPTZDirectionRequest.SerializeToString,
                response_deserializer=camera__pb2.StatusResponse.FromString,
                _registered_method=True)


class CameraServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MovePTZ(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetZoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentZoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSpeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetManualGps(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCrossPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPTZPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPTZDirection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelemetry,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.TelemetryResponse.SerializeToString,
            ),
            'MovePTZ': grpc.unary_unary_rpc_method_handler(
                    servicer.MovePTZ,
                    request_deserializer=camera__pb2.MovePTZRequest.FromString,
                    response_serializer=camera__pb2.StatusResponse.SerializeToString,
            ),
            'SetZoom': grpc.unary_unary_rpc_method_handler(
                    servicer.SetZoom,
                    request_deserializer=camera__pb2.SetZoomRequest.FromString,
                    response_serializer=camera__pb2.StatusResponse.SerializeToString,
            ),
            'GetCurrentZoom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentZoom,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.ZoomResponse.SerializeToString,
            ),
            'SetSpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSpeed,
                    request_deserializer=camera__pb2.SetSpeedRequest.FromString,
                    response_serializer=camera__pb2.StatusResponse.SerializeToString,
            ),
            'SetManualGps': grpc.unary_unary_rpc_method_handler(
                    servicer.SetManualGps,
                    request_deserializer=camera__pb2.ManualGpsRequest.FromString,
                    response_serializer=camera__pb2.StatusResponse.SerializeToString,
            ),
            'GetCrossPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCrossPositions,
                    request_deserializer=camera__pb2.CrossPositionsRequest.FromString,
                    response_serializer=camera__pb2.CrossPositionsResponse.SerializeToString,
            ),
            'GetPTZPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPTZPosition,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.PTZPositionResponse.SerializeToString,
            ),
            'SendControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SendControl,
                    request_deserializer=camera__pb2.SendControlRequest.FromString,
                    response_serializer=camera__pb2.StatusResponse.SerializeToString,
            ),
            'SetPTZDirection': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPTZDirection,
                    request_deserializer=camera__pb2.SetPTZDirectionRequest.FromString,
                    response_serializer=camera__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'camera.CameraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('camera.CameraService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CameraService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.CameraService/GetTelemetry',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.TelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MovePTZ(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.CameraService/MovePTZ',
            camera__pb2.MovePTZRequest.SerializeToString,
            camera__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetZoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.CameraService/SetZoom',
            camera__pb2.SetZoomRequest.SerializeToString,
            camera__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentZoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.CameraService/GetCurrentZoom',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.ZoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.CameraService/SetSpeed',
            camera__pb2.SetSpeedRequest.SerializeToString,
            camera__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetManualGps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.CameraService/SetManualGps',
            camera__pb2.ManualGpsRequest.SerializeToString,
            camera__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCrossPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.CameraService/GetCrossPositions',
            camera__pb2.CrossPositionsRequest.SerializeToString,
            camera__pb2.CrossPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPTZPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.CameraService/GetPTZPosition',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.PTZPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.CameraService/SendControl',
            camera__pb2.SendControlRequest.SerializeToString,
            camera__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPTZDirection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.CameraService/SetPTZDirection',
            camera__pb2.SetPTZDirectionRequest.SerializeToString,
            camera__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
